"""initial schema

Revision ID: 2a16d38c203b
Revises: 
Create Date: 2026-09-06 05:29:36.941474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a16d38c203b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('CREATOR', 'INFLUENCER', 'FREELANCER', 'CREATOR_MANAGER', 'AGENCY', 'BRAND', 'BRAND_MEMBER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', 'DEACTIVATED', name='userstatus'), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sa.Enum('PRICING_ACCESSED', 'CONTACT_ACCESSED', 'VERIFICATION_CHANGED', 'CAMPAIGN_CHANGED', 'ACCOUNT_DISCONNECTED', 'ADMIN_ACTION', 'LOGIN', 'LOGOUT', name='auditaction'), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('brand_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verification_status', sa.Enum('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED', 'NEEDS_ATTENTION', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_profiles_company_slug'), ['company_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_brand_profiles_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_brand_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_brand_profiles_verification_status'), ['verification_status'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('creator_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_type', sa.Enum('INFLUENCER', 'CONTENT_CREATOR', 'UGC_CREATOR', 'FREELANCER', 'CREATOR_FREELANCER', 'OTHER', name='creatortype'), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('niches', sa.JSON(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('response_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_completion', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.Enum('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED', 'NEEDS_ATTENTION', name='verificationstatus'), nullable=False),
    sa.Column('contact_visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_profiles_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_profiles_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_profiles_creator_type'), ['creator_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_profiles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_creator_profiles_verification_status'), ['verification_status'], unique=False)

    op.create_table('freelancer_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('project_rate', sa.Float(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED', 'NEEDS_ATTENTION', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('freelancer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_freelancer_profiles_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_freelancer_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('MESSAGE', 'CAMPAIGN', 'PROFILE_VIEW', 'OPPORTUNITY', 'VERIFICATION', 'SOCIAL_SYNC', 'SAVED_SEARCH', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('social_accounts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'YOUTUBE', 'TIKTOK', 'FACEBOOK', 'LINKEDIN', 'X', 'PINTEREST', 'TWITCH', 'SNAPCHAT', 'THREADS', name='platform'), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('access_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.Enum('NEVER_SYNCED', 'SYNCING', 'SYNCED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('sync_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_accounts_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_accounts_sync_status'), ['sync_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('verification_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'PHONE', 'IDENTITY', 'SOCIAL_OWNERSHIP', 'BUSINESS', 'PROFESSIONAL', name='verificationtype'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED', 'NEEDS_ATTENTION', name='verificationstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_records_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_records_user_id'), ['user_id'], unique=False)

    op.create_table('audience_snapshots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('social_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_snapshots_social_account_id'), ['social_account_id'], unique=False)

    op.create_table('brand_presenter_scores',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('audience_quality', sa.Integer(), nullable=False),
    sa.Column('engagement_quality', sa.Integer(), nullable=False),
    sa.Column('content_performance', sa.Integer(), nullable=False),
    sa.Column('consistency', sa.Integer(), nullable=False),
    sa.Column('brand_fit', sa.Integer(), nullable=False),
    sa.Column('professional_reliability', sa.Integer(), nullable=False),
    sa.Column('commercial_value', sa.Integer(), nullable=False),
    sa.Column('methodology_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_presenter_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_presenter_scores_creator_id'), ['creator_id'], unique=True)

    op.create_table('campaigns',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'INVITED', 'NEGOTIATING', 'ACCEPTED', 'IN_PROGRESS', 'CONTENT_SUBMITTED', 'REVIEW', 'APPROVED', 'PUBLISHED', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='campaignstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatrole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('content_metrics',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('social_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_type', sa.Enum('POST', 'REEL', 'SHORT', 'VIDEO', 'STORY', 'LIVE', 'ARTICLE', 'THREAD', 'OTHER', name='contenttype'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('watch_time', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_metrics_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_metrics_social_account_id'), ['social_account_id'], unique=False)

    op.create_table('creator_pricing',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'YOUTUBE', 'TIKTOK', 'FACEBOOK', 'LINKEDIN', 'X', 'PINTEREST', 'TWITCH', 'SNAPCHAT', 'THREADS', name='platform'), nullable=False),
    sa.Column('content_type', sa.Enum('POST', 'REEL', 'SHORT', 'VIDEO', 'STORY', 'LIVE', 'ARTICLE', 'THREAD', 'OTHER', name='contenttype'), nullable=False),
    sa.Column('service_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pricing_model', sa.Enum('FIXED', 'RANGE', 'STARTING_FROM', 'NEGOTIABLE', name='pricingmodel'), nullable=False),
    sa.Column('is_negotiable', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'VERIFIED_BRANDS', 'PRIVATE', name='pricingvisibility'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_pricing_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_pricing_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_pricing_visibility'), ['visibility'], unique=False)

    op.create_table('metric_snapshots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('social_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('measurement_start', sa.DateTime(), nullable=True),
    sa.Column('measurement_end', sa.DateTime(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('average_views', sa.Float(), nullable=True),
    sa.Column('average_reach', sa.Float(), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('website_clicks', sa.Integer(), nullable=True),
    sa.Column('growth_absolute', sa.Integer(), nullable=True),
    sa.Column('growth_percentage', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sync_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_engagement_rate'), ['engagement_rate'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_followers'), ['followers'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_social_account_id'), ['social_account_id'], unique=False)

    op.create_table('portfolio_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'YOUTUBE', 'TIKTOK', 'FACEBOOK', 'LINKEDIN', 'X', 'PINTEREST', 'TWITCH', 'SNAPCHAT', 'THREADS', name='platform'), nullable=True),
    sa.Column('content_type', sa.Enum('POST', 'REEL', 'SHORT', 'VIDEO', 'STORY', 'LIVE', 'ARTICLE', 'THREAD', 'OTHER', name='contenttype'), nullable=False),
    sa.Column('content_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Enum('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED', 'NEEDS_ATTENTION', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_items_creator_id'), ['creator_id'], unique=False)

    op.create_table('profile_views',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('viewer_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_views_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_views_viewed_at'), ['viewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_views_viewer_user_id'), ['viewer_user_id'], unique=False)

    op.create_table('saved_searches',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_searches_brand_id'), ['brand_id'], unique=False)

    op.create_table('shortlists',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shortlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shortlists_brand_id'), ['brand_id'], unique=False)

    op.create_table('audience_ages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age_range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['audience_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_ages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_ages_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('audience_cities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['audience_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_cities_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('audience_countries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['audience_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_countries_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('audience_genders',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['audience_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_genders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_genders_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('audience_interests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['audience_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_interests_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('audience_languages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['audience_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_languages_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('campaign_creators',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'NEGOTIATING', 'ACCEPTED', 'DECLINED', 'COMPLETED', name='campaigncreatorstatus'), nullable=False),
    sa.Column('agreed_price', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_creators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_creators_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_creators_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_creators_status'), ['status'], unique=False)

    op.create_table('campaign_deliverables',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'YOUTUBE', 'TIKTOK', 'FACEBOOK', 'LINKEDIN', 'X', 'PINTEREST', 'TWITCH', 'SNAPCHAT', 'THREADS', name='platform'), nullable=True),
    sa.Column('content_type', sa.Enum('POST', 'REEL', 'SHORT', 'VIDEO', 'STORY', 'LIVE', 'ARTICLE', 'THREAD', 'OTHER', name='contenttype'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'SUBMITTED', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'COMPLETED', name='deliverablestatus'), nullable=False),
    sa.Column('content_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_deliverables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_deliverables_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_deliverables_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_deliverables_status'), ['status'], unique=False)

    op.create_table('campaign_usage_rights',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('territory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage_type', sa.Enum('ORGANIC', 'PAID', 'WHITELISTING', 'SPARK_ADS', 'EXCLUSIVITY', name='usagetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('paid_usage', sa.Boolean(), nullable=False),
    sa.Column('whitelisting', sa.Boolean(), nullable=False),
    sa.Column('exclusivity', sa.Boolean(), nullable=False),
    sa.Column('ownership_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_usage_rights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_usage_rights_campaign_id'), ['campaign_id'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_updated_at'), ['updated_at'], unique=False)

    op.create_table('shortlist_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shortlist_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.ForeignKeyConstraint(['shortlist_id'], ['shortlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shortlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shortlist_items_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shortlist_items_shortlist_id'), ['shortlist_id'], unique=False)

    op.create_table('conversation_participants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_participants_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'SYSTEM', 'CAMPAIGN', 'PROPOSAL', 'FILE', 'AI_ASSISTED', name='messagetype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_participants_conversation_id'))

    op.drop_table('conversation_participants')
    with op.batch_alter_table('shortlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shortlist_items_shortlist_id'))
        batch_op.drop_index(batch_op.f('ix_shortlist_items_creator_id'))

    op.drop_table('shortlist_items')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_campaign_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('campaign_usage_rights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_usage_rights_campaign_id'))

    op.drop_table('campaign_usage_rights')
    with op.batch_alter_table('campaign_deliverables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_deliverables_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_deliverables_creator_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_deliverables_campaign_id'))

    op.drop_table('campaign_deliverables')
    with op.batch_alter_table('campaign_creators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_creators_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_creators_creator_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_creators_campaign_id'))

    op.drop_table('campaign_creators')
    with op.batch_alter_table('audience_languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_languages_snapshot_id'))

    op.drop_table('audience_languages')
    with op.batch_alter_table('audience_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_interests_snapshot_id'))

    op.drop_table('audience_interests')
    with op.batch_alter_table('audience_genders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_genders_snapshot_id'))

    op.drop_table('audience_genders')
    with op.batch_alter_table('audience_countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_countries_snapshot_id'))

    op.drop_table('audience_countries')
    with op.batch_alter_table('audience_cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_cities_snapshot_id'))

    op.drop_table('audience_cities')
    with op.batch_alter_table('audience_ages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_ages_snapshot_id'))

    op.drop_table('audience_ages')
    with op.batch_alter_table('shortlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shortlists_brand_id'))

    op.drop_table('shortlists')
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_searches_brand_id'))

    op.drop_table('saved_searches')
    with op.batch_alter_table('profile_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_views_viewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_profile_views_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_profile_views_creator_id'))

    op.drop_table('profile_views')
    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_items_creator_id'))

    op.drop_table('portfolio_items')
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_social_account_id'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_followers'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_engagement_rate'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_captured_at'))

    op.drop_table('metric_snapshots')
    with op.batch_alter_table('creator_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_pricing_visibility'))
        batch_op.drop_index(batch_op.f('ix_creator_pricing_platform'))
        batch_op.drop_index(batch_op.f('ix_creator_pricing_creator_id'))

    op.drop_table('creator_pricing')
    with op.batch_alter_table('content_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_metrics_social_account_id'))
        batch_op.drop_index(batch_op.f('ix_content_metrics_published_at'))

    op.drop_table('content_metrics')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_brand_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('brand_presenter_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_presenter_scores_creator_id'))

    op.drop_table('brand_presenter_scores')
    with op.batch_alter_table('audience_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_snapshots_social_account_id'))
        batch_op.drop_index(batch_op.f('ix_audience_snapshots_captured_at'))

    op.drop_table('audience_snapshots')
    with op.batch_alter_table('verification_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_verification_records_type'))
        batch_op.drop_index(batch_op.f('ix_verification_records_status'))

    op.drop_table('verification_records')
    with op.batch_alter_table('social_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_social_accounts_sync_status'))
        batch_op.drop_index(batch_op.f('ix_social_accounts_platform'))

    op.drop_table('social_accounts')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('freelancer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_freelancer_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_freelancer_profiles_country'))

    op.drop_table('freelancer_profiles')
    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_profiles_verification_status'))
        batch_op.drop_index(batch_op.f('ix_creator_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_creator_profiles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_creator_profiles_creator_type'))
        batch_op.drop_index(batch_op.f('ix_creator_profiles_created_at'))
        batch_op.drop_index(batch_op.f('ix_creator_profiles_country'))
        batch_op.drop_index(batch_op.f('ix_creator_profiles_city'))

    op.drop_table('creator_profiles')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_updated_at'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('brand_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_profiles_verification_status'))
        batch_op.drop_index(batch_op.f('ix_brand_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_brand_profiles_country'))
        batch_op.drop_index(batch_op.f('ix_brand_profiles_company_slug'))

    op.drop_table('brand_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
